<a href="https://colab.research.google.com/github/chetanbalaji-star/Home-infusion-therapy/blob/main/Home_infusion_therapy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import the libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

Load and Prepare the data

In [3]:
data = pd.read_csv('/content/Home_Infusion_Therapy_Providers.csv')

In [4]:
pd.read_csv?

In [5]:
data.head()

,Enrollment ID,Legal Business Name,Street Address Line 1,Street Address Line 2,City,State,ZIP Code,Practice Location Phone Number,Specialty Name,Geographic Location Type Description,Geographic Location City Name,Geographic Location State Code,Geographic Location ZIP Code,State County Name
0,O20210121000184,I.V. SOLUTIONS LLC,165 HANSEN CT,STE 106,WOOD DALE,IL,60191-1110,8479454444-1110,HOME INFUSION THERAPY,RENDERING AREA,--,IL,--,LAKE
1,O20210121000184,I.V. SOLUTIONS LLC,165 HANSEN CT,STE 106,WOOD DALE,IL,60191-1110,8479454444-1110,HOME INFUSION THERAPY,RENDERING AREA,--,IL,--,KANE
2,O20210218002079,COMPLETE INFUSION SVCS LLC,28550 CABOT DR,STE 200,NOVI,MI,48377-2988,(866) 425-2550,HOME INFUSION THERAPY,RENDERING AREA,--,MI,--,--
3,O20210826002187,INFUSION SOLUTIONS INC,477 W HORTON RD,--,BELLINGHAM,WA,98226-1205,(360) 933-4892,HOME INFUSION THERAPY,SUPPLIER GR. AREA,--,WA,--,--
4,O20210416000228,CATHOLIC HEALTH SYSTEM INFUS,6350 TRANSIT RD,--,DEPEW,NY,14043-1039,(716) 685-4870,HOME INFUSION THERAPY,RENDERING AREA,EAST AURORA,NY,--,--

In [6]:
data.shape

(2284, 14)

In [7]:
data.describe()

,Enrollment ID,Legal Business Name,Street Address Line 1,Street Address Line 2,City,State,ZIP Code,Practice Location Phone Number,Specialty Name,Geographic Location Type Description,Geographic Location City Name,Geographic Location State Code,Geographic Location ZIP Code,State County Name
count,2284,2284,2284,2284,2284,2284,2284,2284,2284,2284,2284,2284,2284,2284
unique,362,231,418,156,306,47,422,401,1,3,582,54,3,389
top,O20230113001397,PRESENCE HOME CARE,2347 HONOLULU AVE,--,MONTROSE,CA,91020-1821,(818) 241-4444,HOME INFUSION THERAPY,RENDERING AREA,--,CA,--,--
freq,198,207,198,974,198,405,198,198,2284,1911,1579,396,2281,1282

In [8]:
data['Geographic Location City Name'].value_counts()

Geographic Location City Name
--                      1579
FANNIN                     4
VAN ZANDT                  4
PARKER                     4
COLLIN                     4
                        ...
LA CANADA FLINTRIDGE       1
IRVINE                     1
COSTA MESA                 1
MONROVIA                   1
SYMERTON                   1
Name: count, Length: 582, dtype: int64

In [9]:
data['Enrollment ID'].value_counts()

Enrollment ID
O20230113001397    198
O20201223001304    162
O20210818002720    129
O20210326001947    124
O20220726003369     80
                  ...
O20201202000029      1
O20221229000167      1
O20210621001061      1
O20210119001252      1
O20210324002584      1
Name: count, Length: 362, dtype: int64

In [10]:
data['Legal Business Name'].value_counts()

Legal Business Name
PRESENCE HOME CARE                           207
TARLANI CORP                                 198
HORIZON HOME CARE & HOSPICE                  162
PARAGON INFUSION CARE INC                    130
PROVIDENCE HEALTH & SERVICES - WASHINGTON    124
                                            ...
IMPACT INFUSION CARE LLC                       1
CORAM HEALTHCARE/CAROLINA                      1
INFUSCIENCE, LLC                               1
ACCESS HOME CARE                               1
ETOWN INFUSION PHARMACY LLC                    1
Name: count, Length: 231, dtype: int64

In [12]:
data['Practice Location Phone Number'].value_counts()

Practice Location Phone Number
(818) 241-4444    198
(414) 365-8300    162
(815) 741-7371     80
(877) 828-3940     66
(815) 937-2475     64
                 ...
(210) 646-4888      1
(734) 470-0700      1
(480) 296-0222      1
(217) 383-3488      1
(800) 838-2464      1
Name: count, Length: 401, dtype: int64

In [13]:
data['State County Name'].value_counts()

State County Name
--            1282
JEFFERSON       18
OUTAGAMIE       15
SHEBOYGAN       15
WASHINGTON      15
              ...
JENKINS          1
SALINE           1
PREBLE           1
BUTLER           1
BERGEN           1
Name: count, Length: 389, dtype: int64

In [51]:
X = data.drop(['Street Address Line 2'],axis=1)
y = data['Enrollment ID']

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
  model = RandomForestClassifier(n_estimators=100,random_state=42)

In [52]:
print(X)

        Enrollment ID           Legal Business Name  Street Address Line 1  \
0     O20210121000184            I.V. SOLUTIONS LLC          165 HANSEN CT
1     O20210121000184            I.V. SOLUTIONS LLC          165 HANSEN CT
2     O20210218002079    COMPLETE INFUSION SVCS LLC         28550 CABOT DR
3     O20210826002187        INFUSION SOLUTIONS INC        477 W HORTON RD
4     O20210416000228  CATHOLIC HEALTH SYSTEM INFUS        6350 TRANSIT RD
...               ...                           ...                    ...
2279  O20221128000976     MEDILINK RXCARE HAMMONTON  44 S WHITE HORSE PIKE
2280  O20221128000976     MEDILINK RXCARE HAMMONTON  44 S WHITE HORSE PIKE
2281  O20230320000743        HERITAGE BIOLOGICS LLC     255 NW VICTORIA DR
2282  O20220324002977      ACCREDO HEALTH GROUP INC        650 W GRAND AVE
2283  O20210324002584            KABAFUSION AL, LLC    360F QUALITY CIR NW

             City State    ZIP Code Practice Location Phone Number  \
0       WOOD DALE    IL  60191-1110                8479454444-1110
1       WOOD DALE    IL  60191-1110                8479454444-1110
2            NOVI    MI  48377-2988                 (866) 425-2550
3      BELLINGHAM    WA  98226-1205                 (360) 933-4892
4           DEPEW    NY  14043-1039                 (716) 685-4870
...           ...   ...         ...                            ...
2279    HAMMONTON    NJ  08037-1845                 (609) 956-1900
2280    HAMMONTON    NJ  08037-1845                 (609) 956-1900
2281  LEES SUMMIT    MO  64086-4709                 (855) 937-7273
2282     ELMHURST    IL  60126-1024                 (630) 279-7390
2283   HUNTSVILLE    AL  35806-4546                 (800) 838-2464

             Specialty Name Geographic Location Type Description  \
0     HOME INFUSION THERAPY                       RENDERING AREA
1     HOME INFUSION THERAPY                       RENDERING AREA
2     HOME INFUSION THERAPY                       RENDERING AREA
3     HOME INFUSION THERAPY                    SUPPLIER GR. AREA
4     HOME INFUSION THERAPY                       RENDERING AREA
...                     ...                                  ...
2279  HOME INFUSION THERAPY                       RENDERING AREA
2280  HOME INFUSION THERAPY                       RENDERING AREA
2281  HOME INFUSION THERAPY                       RENDERING AREA
2282  HOME INFUSION THERAPY                                   --
2283  HOME INFUSION THERAPY                                   --

     Geographic Location City Name Geographic Location State Code  \
0                               --                             IL
1                               --                             IL
2                               --                             MI
3                               --                             WA
4                      EAST AURORA                             NY
...                            ...                            ...
2279                            --                             NJ
2280                            --                             NJ
2281                            --                             SD
2282                            --                             --
2283                            --                             --

     Geographic Location ZIP Code State County Name
0                              --              LAKE
1                              --              KANE
2                              --                --
3                              --                --
4                              --                --
...                           ...               ...
2279                           --             OCEAN
2280                           --            BERGEN
2281                           --                --
2282                           --                --
2283                           --                --

[2284 rows x 13 columns]

In [23]:
print(y)

0       O20210121000184
1       O20210121000184
2       O20210218002079
3       O20210826002187
4       O20210416000228
             ...
2279    O20221128000976
2280    O20221128000976
2281    O20230320000743
2282    O20220324002977
2283    O20210324002584
Name: Enrollment ID, Length: 2284, dtype: object

define a function to retrieve patient iformation ny enrollment id

In [18]:
def get_patient_info(enrollment_id):
  patient_info = data[data['Enrollment ID']==enrollment_id]
  if patient_data.empty:
    return "patient not found"
  else:
    return patient_info

define a function to predict treatment outcome

In [24]:
def predict_treatment_outcome(enrollment_id):
  patient_info = get_patient_info(enrollment_id)
  if patient_info == "patient not found":
    return patient_info
  else:
    X_new = patient_info.drop(['Specialty Name'],axis=1)
    y_pred = model.predict(X_new)
    return y_pred[0]

In [30]:
def get_patient_info(enrollment_id):
  patient_info = data[data['Enrollment ID']==enrollment_id]
  # Changed 'patient_data' to 'patient_info' in the if statement condition
  if patient_info.empty:
    return "patient not found"
  else:
    return patient_info

test the function

In [65]:
def predict_treatment_outcome(enrollment_id):
  patient_info = get_patient_info(enrollment_id)
  # Check if the DataFrame is empty instead of directly comparing with the string
  if patient_info.empty: # After the change
    return patient_info
  else:
    X_new = patient_info.drop(['Specialty Name'],axis=1)
    y_pred = model.predict(X_new)
    return y_pred[0]

In [72]:
enrollment_id = input("enter the enrollment id:")
# Remove the int() cast to keep it as a string
# If you need to extract the numeric part of the ID:
enrollment_id_numeric = int(''.join(filter(str.isdigit, enrollment_id)))
patient_info = data[data['Enrollment ID']==enrollment_id]
# Assuming predict_treatment_outcome now handles string IDs
print("treatment outcome:",X)

print("The patient of this enrollment id have been enrolled in Home Infusion Therapy.")

enter the enrollment id:O20210121000184
treatment outcome:         Enrollment ID           Legal Business Name  Street Address Line 1  \
0     O20210121000184            I.V. SOLUTIONS LLC          165 HANSEN CT
1     O20210121000184            I.V. SOLUTIONS LLC          165 HANSEN CT
2     O20210218002079    COMPLETE INFUSION SVCS LLC         28550 CABOT DR
3     O20210826002187        INFUSION SOLUTIONS INC        477 W HORTON RD
4     O20210416000228  CATHOLIC HEALTH SYSTEM INFUS        6350 TRANSIT RD
...               ...                           ...                    ...
2279  O20221128000976     MEDILINK RXCARE HAMMONTON  44 S WHITE HORSE PIKE
2280  O20221128000976     MEDILINK RXCARE HAMMONTON  44 S WHITE HORSE PIKE
2281  O20230320000743        HERITAGE BIOLOGICS LLC     255 NW VICTORIA DR
2282  O20220324002977      ACCREDO HEALTH GROUP INC        650 W GRAND AVE
2283  O20210324002584            KABAFUSION AL, LLC    360F QUALITY CIR NW

             City State    ZIP Code Practice Location Phone Number  \
0       WOOD DALE    IL  60191-1110                8479454444-1110
1       WOOD DALE    IL  60191-1110                8479454444-1110
2            NOVI    MI  48377-2988                 (866) 425-2550
3      BELLINGHAM    WA  98226-1205                 (360) 933-4892
4           DEPEW    NY  14043-1039                 (716) 685-4870
...           ...   ...         ...                            ...
2279    HAMMONTON    NJ  08037-1845                 (609) 956-1900
2280    HAMMONTON    NJ  08037-1845                 (609) 956-1900
2281  LEES SUMMIT    MO  64086-4709                 (855) 937-7273
2282     ELMHURST    IL  60126-1024                 (630) 279-7390
2283   HUNTSVILLE    AL  35806-4546                 (800) 838-2464

             Specialty Name Geographic Location Type Description  \
0     HOME INFUSION THERAPY                       RENDERING AREA
1     HOME INFUSION THERAPY                       RENDERING AREA
2     HOME INFUSION THERAPY                       RENDERING AREA
3     HOME INFUSION THERAPY                    SUPPLIER GR. AREA
4     HOME INFUSION THERAPY                       RENDERING AREA
...                     ...                                  ...
2279  HOME INFUSION THERAPY                       RENDERING AREA
2280  HOME INFUSION THERAPY                       RENDERING AREA
2281  HOME INFUSION THERAPY                       RENDERING AREA
2282  HOME INFUSION THERAPY                                   --
2283  HOME INFUSION THERAPY                                   --

     Geographic Location City Name Geographic Location State Code  \
0                               --                             IL
1                               --                             IL
2                               --                             MI
3                               --                             WA
4                      EAST AURORA                             NY
...                            ...                            ...
2279                            --                             NJ
2280                            --                             NJ
2281                            --                             SD
2282                            --                             --
2283                            --                             --

     Geographic Location ZIP Code State County Name
0                              --              LAKE
1                              --              KANE
2                              --                --
3                              --                --
4                              --                --
...                           ...               ...
2279                           --             OCEAN
2280                           --            BERGEN
2281                           --                --
2282                           --                --
2283                           --                --

[2284 rows x 13 columns]
The patient of this enrollment id have been enrolled in Home Infusion Therapy.

In [81]:
enrollment_id = input("enter the enrollment id:")
# Remove the int() cast to keep it as a string
# If you need to extract the numeric part of the ID:
enrollment_id_numeric = int(''.join(filter(str.isdigit, enrollment_id)))
patient_info = data[data['Enrollment ID']==enrollment_id]
# Assuming predict_treatment_outcome now handles string IDs
print("treatment outcome:",X)
if patient_info.empty: # After the change
  print("patient not found")
else:
  print("The patient of this enrollment id have been enrolled in Home Infusion Therapy.")

enter the enrollment id:O20221128000976
treatment outcome:         Enrollment ID           Legal Business Name  Street Address Line 1  \
0     O20210121000184            I.V. SOLUTIONS LLC          165 HANSEN CT
1     O20210121000184            I.V. SOLUTIONS LLC          165 HANSEN CT
2     O20210218002079    COMPLETE INFUSION SVCS LLC         28550 CABOT DR
3     O20210826002187        INFUSION SOLUTIONS INC        477 W HORTON RD
4     O20210416000228  CATHOLIC HEALTH SYSTEM INFUS        6350 TRANSIT RD
...               ...                           ...                    ...
2279  O20221128000976     MEDILINK RXCARE HAMMONTON  44 S WHITE HORSE PIKE
2280  O20221128000976     MEDILINK RXCARE HAMMONTON  44 S WHITE HORSE PIKE
2281  O20230320000743        HERITAGE BIOLOGICS LLC     255 NW VICTORIA DR
2282  O20220324002977      ACCREDO HEALTH GROUP INC        650 W GRAND AVE
2283  O20210324002584            KABAFUSION AL, LLC    360F QUALITY CIR NW

             City State    ZIP Code Practice Location Phone Number  \
0       WOOD DALE    IL  60191-1110                8479454444-1110
1       WOOD DALE    IL  60191-1110                8479454444-1110
2            NOVI    MI  48377-2988                 (866) 425-2550
3      BELLINGHAM    WA  98226-1205                 (360) 933-4892
4           DEPEW    NY  14043-1039                 (716) 685-4870
...           ...   ...         ...                            ...
2279    HAMMONTON    NJ  08037-1845                 (609) 956-1900
2280    HAMMONTON    NJ  08037-1845                 (609) 956-1900
2281  LEES SUMMIT    MO  64086-4709                 (855) 937-7273
2282     ELMHURST    IL  60126-1024                 (630) 279-7390
2283   HUNTSVILLE    AL  35806-4546                 (800) 838-2464

             Specialty Name Geographic Location Type Description  \
0     HOME INFUSION THERAPY                       RENDERING AREA
1     HOME INFUSION THERAPY                       RENDERING AREA
2     HOME INFUSION THERAPY                       RENDERING AREA
3     HOME INFUSION THERAPY                    SUPPLIER GR. AREA
4     HOME INFUSION THERAPY                       RENDERING AREA
...                     ...                                  ...
2279  HOME INFUSION THERAPY                       RENDERING AREA
2280  HOME INFUSION THERAPY                       RENDERING AREA
2281  HOME INFUSION THERAPY                       RENDERING AREA
2282  HOME INFUSION THERAPY                                   --
2283  HOME INFUSION THERAPY                                   --

     Geographic Location City Name Geographic Location State Code  \
0                               --                             IL
1                               --                             IL
2                               --                             MI
3                               --                             WA
4                      EAST AURORA                             NY
...                            ...                            ...
2279                            --                             NJ
2280                            --                             NJ
2281                            --                             SD
2282                            --                             --
2283                            --                             --

     Geographic Location ZIP Code State County Name
0                              --              LAKE
1                              --              KANE
2                              --                --
3                              --                --
4                              --                --
...                           ...               ...
2279                           --             OCEAN
2280                           --            BERGEN
2281                           --                --
2282                           --                --
2283                           --                --

[2284 rows x 13 columns]
patient not found

In [ ]:
enrollment_id = input("enter the enrollment id:")
# Remove the int() cast to keep it as a string
# If you need to extract the numeric part of the ID:
enrollment_id_numeric = int(''.join(filter(str.isdigit, enrollment_id)))
patient_info = data[data['Enrollment ID']==enrollment_id]
# Assuming predict_treatment_outcome now handles string IDs
print("treatment outcome:",X)
if patient_info.empty: # After the change
  print("patient not found")
else:
  print("The patient of this enrollment id have been enrolled in Home Infusion Therapy.")